# Generated by Django 4.0 on 2021-12-22 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_rename_timestamp_todo_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='uuid',
            field=models.CharField(blank=True, max_length=36, null=True, unique=True),
        ),
    ]
