# Generated by Django 4.0 on 2021-12-22 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_todo_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='uuid',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='uuid',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
